// Interface automatically generated by schemas-to-ts

export enum WeightUnit {
  Kg = 'kg',
  Lb = 'lb',}

export interface WorkoutSet {
  weight?: number;
  weightUnit?: WeightUnit;
  reps?: number;
  rp?: number;
}
export interface WorkoutSet_Plain {
  weight?: number;
  weightUnit?: WeightUnit;
  reps?: number;
  rp?: number;
}

export interface WorkoutSet_NoRelations {
  weight?: number;
  weightUnit?: WeightUnit;
  reps?: number;
  rp?: number;
}

