// Interface automatically generated by schemas-to-ts

import { Exercise } from '../../../api/exercise/content-types/exercise/exercise';
import { WorkoutSet } from './WorkoutSet';
import { Exercise_Plain } from '../../../api/exercise/content-types/exercise/exercise';
import { WorkoutSet_Plain } from './WorkoutSet';
import { WorkoutSet_NoRelations } from './WorkoutSet';

export interface WorkoutExercise {
  exercise?: { data: Exercise };
  sets: WorkoutSet[];
}
export interface WorkoutExercise_Plain {
  exercise?: Exercise_Plain;
  sets: WorkoutSet_Plain[];
}

export interface WorkoutExercise_NoRelations {
  exercise?: number;
  sets: WorkoutSet_NoRelations[];
}

