// Interface automatically generated by schemas-to-ts

import { Exercise } from '../../../api/exercise/content-types/exercise/exercise';
import { Exercise_Plain } from '../../../api/exercise/content-types/exercise/exercise';

export interface WorkoutExercise {
  exercise?: { data: Exercise };
  weight?: number;
  sets?: number;
  reps?: number;
}
export interface WorkoutExercise_Plain {
  exercise?: Exercise_Plain;
  weight?: number;
  sets?: number;
  reps?: number;
}

export interface WorkoutExercise_NoRelations {
  exercise?: number;
  weight?: number;
  sets?: number;
  reps?: number;
}

