// Interface automatically generated by schemas-to-ts

import { WorkoutExercise } from '../../../../components/workout/interfaces/WorkoutExercise';
import { WorkoutExercise_Plain } from '../../../../components/workout/interfaces/WorkoutExercise';
import { WorkoutExercise_NoRelations } from '../../../../components/workout/interfaces/WorkoutExercise';

export interface Workout {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    userId: string;
    date: Date;
    duration: number;
    calories_estimate?: number;
    exercises: WorkoutExercise[];
  };
}
export interface Workout_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  userId: string;
  date: Date;
  duration: number;
  calories_estimate?: number;
  exercises: WorkoutExercise_Plain[];
}

export interface Workout_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  userId: string;
  date: Date;
  duration: number;
  calories_estimate?: number;
  exercises: WorkoutExercise_NoRelations[];
}

export interface Workout_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  userId: string;
  date: Date;
  duration: number;
  calories_estimate?: number;
  exercises: WorkoutExercise_Plain[];
}
