// Interface automatically generated by schemas-to-ts

export interface Workout {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    userId: string;
    date: Date;
    duration: number;
    exercises?: any;
  };
}
export interface Workout_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  userId: string;
  date: Date;
  duration: number;
  exercises?: any;
}

export interface Workout_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  userId: string;
  date: Date;
  duration: number;
  exercises?: any;
}

export interface Workout_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  userId: string;
  date: Date;
  duration: number;
  exercises?: any;
}
