// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Difficulty {
  Beginner = 'Beginner',
  Intermediate = 'Intermediate',
  Advanced = 'Advanced',}

export interface Exercise {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    description?: string;
    difficulty?: Difficulty;
    image?: { data: Media };
    videoUrl?: string;
    isActive?: boolean;
  };
}
export interface Exercise_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: string;
  difficulty?: Difficulty;
  image?: Media_Plain;
  videoUrl?: string;
  isActive?: boolean;
}

export interface Exercise_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: string;
  difficulty?: Difficulty;
  image?: number;
  videoUrl?: string;
  isActive?: boolean;
}

export interface Exercise_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: string;
  difficulty?: Difficulty;
  image?: AdminPanelRelationPropertyModification<Media_Plain>;
  videoUrl?: string;
  isActive?: boolean;
}
